/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Deposit, DepositInterface } from "../Deposit";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a3806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063c4d66de814610030575b600080fd5b61004a600480360381019061004591906101c3565b61004c565b005b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16146100dc576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100d39061024d565b60405180910390fd5b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555033600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061019082610165565b9050919050565b6101a081610185565b81146101ab57600080fd5b50565b6000813590506101bd81610197565b92915050565b6000602082840312156101d9576101d8610160565b5b60006101e7848285016101ae565b91505092915050565b600082825260208201905092915050565b7f4465706f7369743a20464f5242494444454e0000000000000000000000000000600082015250565b60006102376012836101f0565b915061024282610201565b602082019050919050565b600060208201905081810360008301526102668161022a565b905091905056fea264697066735822122037043d3e9dfc4f14bc6044eeec6bb28181e61033c460abff97f3caeab58dbbae64736f6c63430008090033";

export class Deposit__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Deposit> {
    return super.deploy(overrides || {}) as Promise<Deposit>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Deposit {
    return super.attach(address) as Deposit;
  }
  connect(signer: Signer): Deposit__factory {
    return super.connect(signer) as Deposit__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DepositInterface {
    return new utils.Interface(_abi) as DepositInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Deposit {
    return new Contract(address, _abi, signerOrProvider) as Deposit;
  }
}
