/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IDeposit, IDepositInterface } from "../IDeposit";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDeposit__factory {
  static readonly abi = _abi;
  static createInterface(): IDepositInterface {
    return new utils.Interface(_abi) as IDepositInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDeposit {
    return new Contract(address, _abi, signerOrProvider) as IDeposit;
  }
}
