@startuml
title Game Login (SDK)

actor User

participant GameUI
participant VoyageSDK
participant VoyageCRX
note over VoyageCRX: Chrome extension

User -> GameUI : Sign In with Voyage
GameUI -> VoyageSDK : connect()
VoyageSDK -> VoyageCRX : connect()
alt not signed in
	VoyageCRX --> User : Game wants to get your info. Agree?
	note left: in extension
	User --> VoyageCRX : agree, sign in
	VoyageCRX -> Torus : connect()
	Torus --> VoyageCRX : userInfo
end
VoyageCRX -> VoyageBE : getVaultInfo(userInfo)
VoyageBE -> Node : voyage.getVaultInfo(userAddress)
Node --> VoyageBE : vaultInfo
VoyageBE --> VoyageCRX: vaultInfo
VoyageCRX --> VoyageSDK : (userInfo, vaultInfo)
VoyageSDK --> GameUI : (email, vaultAddress)
GameUI -> GameBE : bindUserAddress(email, vaultAddress)
GameBE -> GameBE : sendOTP(email)
GameBE --> GameUI : accountId
GameUI --> User : request OTP
note left: in-browser, async
User -> GameUI : input OTP
GameUI -> GameBE : validate OTP
GameBE --> GameUI : valid
GameUI --> User : login success
@enduml