/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IReserveManagerInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "ReserveActivated(address)": EventFragment;
    "ReserveDeactivated(address)": EventFragment;
    "ReserveInitialized(address,address,address,address)": EventFragment;
    "ReserveUpdated(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReserveActivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveDeactivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveInitialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReserveUpdated"): EventFragment;
}

export type ReserveActivatedEvent = TypedEvent<[string] & { _reserve: string }>;

export type ReserveDeactivatedEvent = TypedEvent<
  [string] & { _reserve: string }
>;

export type ReserveInitializedEvent = TypedEvent<
  [string, string, string, string] & {
    _reserve: string;
    _jdToken: string;
    _sdToken: string;
    _interestRateStrategyAddress: string;
  }
>;

export type ReserveUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber] & {
    reserve: string;
    liquidityRate: BigNumber;
    currentJuniorLiquidityIndex: BigNumber;
    currentSeniorLiquidityIndex: BigNumber;
  }
>;

export class IReserveManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IReserveManagerInterface;

  functions: {};

  callStatic: {};

  filters: {
    "ReserveActivated(address)"(
      _reserve?: string | null
    ): TypedEventFilter<[string], { _reserve: string }>;

    ReserveActivated(
      _reserve?: string | null
    ): TypedEventFilter<[string], { _reserve: string }>;

    "ReserveDeactivated(address)"(
      _reserve?: string | null
    ): TypedEventFilter<[string], { _reserve: string }>;

    ReserveDeactivated(
      _reserve?: string | null
    ): TypedEventFilter<[string], { _reserve: string }>;

    "ReserveInitialized(address,address,address,address)"(
      _reserve?: string | null,
      _jdToken?: string | null,
      _sdToken?: string | null,
      _interestRateStrategyAddress?: null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        _reserve: string;
        _jdToken: string;
        _sdToken: string;
        _interestRateStrategyAddress: string;
      }
    >;

    ReserveInitialized(
      _reserve?: string | null,
      _jdToken?: string | null,
      _sdToken?: string | null,
      _interestRateStrategyAddress?: null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        _reserve: string;
        _jdToken: string;
        _sdToken: string;
        _interestRateStrategyAddress: string;
      }
    >;

    "ReserveUpdated(address,uint256,uint256,uint256)"(
      reserve?: string | null,
      liquidityRate?: null,
      currentJuniorLiquidityIndex?: null,
      currentSeniorLiquidityIndex?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        reserve: string;
        liquidityRate: BigNumber;
        currentJuniorLiquidityIndex: BigNumber;
        currentSeniorLiquidityIndex: BigNumber;
      }
    >;

    ReserveUpdated(
      reserve?: string | null,
      liquidityRate?: null,
      currentJuniorLiquidityIndex?: null,
      currentSeniorLiquidityIndex?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        reserve: string;
        liquidityRate: BigNumber;
        currentJuniorLiquidityIndex: BigNumber;
        currentSeniorLiquidityIndex: BigNumber;
      }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
