name: Check

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - run: yarn install
      - run:  GOERLI_MNEMONIC=`${{ secrets.GOERLI_MNEMONIC }}` yarn compile
      - run:  GOERLI_MNEMONIC=`${{ secrets.GOERLI_MNEMONIC }}` yarn check:hh
      - run:  GOERLI_MNEMONIC=`${{ secrets.GOERLI_MNEMONIC }}` RELAY_HUB=`${{ secrets.RELAY_HUB }}` TRUSTED_FORWARDER=`${{ secrets.TRUSTED_FORWARDER }}` yarn cov 
